
# working_directory = "$HOME"

[env]
TERM = "xterm-256color"

[font]

size = 15.0
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[window]

[general]
import = ["~/.config/alacritty/theme/dracula.toml"]

# decorations = "Buttonless"
